# Generated by Django 4.1.5 on 2023-10-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_app", "0002_home_home_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="myOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("otps", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
